print("Known Issues:")
print()
print("1. When viewing the main website on mobile, the navbar works but the nav menu is not visible even when toggled and is covered and only a small sliver is visible.")
print()
print("2. When scrolling the blur effect on the navbar flashes ocasionally. (this is not a really big issue but it is annoying and visually unpleasing)")
print()
print()
print()
print("Notes:")
print()
print("There have been several attempts to fix these issues by both me, Microsoft Copilot, and the Replit AI but none have been successful as the issues still persist and the fixes have either not worked or have broken other parts of the website.")